
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kmgbbcwsupzcoevaolva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_kVOM2l-u9NbRKcQOutdLZg_6N2xMDhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => await fn(),
  },
});
