
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kmgbbcwsupzcoevaolva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ2JiY3dzdXB6Y29ldmFvbHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MzkwODQsImV4cCI6MjA4NzQxNTA4NH0.g2NnbzPQQYCqRN9C0Lp3n4-Wd5B9K449mfoxd3vbnfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    lock: async (_name: string, _acquireTimeout: number, fn: () => Promise<any>) => await fn(),
  },
});
